-- @description hsuanice_Pro Tools Consolidate Selection
-- @version 0.1.0 [260415.1250]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper replicating Pro Tools: **Consolidate Selection**
--
--   ## Mapping
--   - Pro Tools equivalent : Consolidate Selection
--   - Reaper action        : Item: Glue items within time selection
--   - Command ID           : 42432
--   - Mac shortcut (PT)    : Option + Shift + 3
--   - Tags                 : Edit menu, Editing
--
-- @changelog
--   0.1.0 [260415.1250]
--     - Initial release
--     - Maps to Reaper command ID 42432

reaper.Main_OnCommand(42432, 0)
