-- @description hsuanice_Pro Tools Slip Mode
-- @version 0.1.0 [260416.1323]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper replicating Pro Tools: **Slip Mode**
--
--   ## Mapping
--   - Pro Tools equivalent : Slip Mode
--   - Reaper action        : Snapping: Disable snap
--   - Command ID           : 40753
--   - Mac shortcut (PT)    : F2
--   - Tags                 : Edit Tools, Editing
--
-- @changelog
--   0.1.0 [260416.1323]
--     - Initial release
--     - Maps Pro Tools "Slip Mode" to Reaper command ID 40753

reaper.Main_OnCommand(40753, 0)
