-- @description hsuanice_Pro Tools Zoom Toggle
-- @version 0.1.0 [260416.1323]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper replicating Pro Tools: **Zoom Toggle**
--
--   ## Mapping
--   - Pro Tools equivalent : Zoom Toggle
--   - Reaper action        : View: Toggle zoom to selected items
--   - Command ID           : 41622
--   - Mac shortcut (PT)    : Control + E
--   - Tags                 : Edit Tools, Zoom
--
-- @changelog
--   0.1.0 [260416.1323]
--     - Initial release
--     - Maps Pro Tools "Zoom Toggle" to Reaper command ID 41622

reaper.Main_OnCommand(41622, 0)
