-- @description hsuanice_Pro Tools Grid Mode
-- @version 0.1.0 [260416.1323]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper replicating Pro Tools: **Grid Mode**
--
--   ## Mapping
--   - Pro Tools equivalent : Grid Mode
--   - Reaper action        : Snapping: Enable snap
--   - Command ID           : 40754
--   - Mac shortcut (PT)    : Option + 4
--   - Tags                 : Edit Tools, Editing
--
-- @changelog
--   0.1.0 [260416.1323]
--     - Initial release
--     - Maps Pro Tools "Grid Mode" to Reaper command ID 40754

reaper.Main_OnCommand(40754, 0)
